import * as responses from './responses.js'

export const parseResponse = (resp) => {
  switch (resp) {
    case 'AuthenticateUser': return new responses.AuthenticateUserResponse(resp)
    case 'Authenticate2FA': return new responses.Authenticate2FAResponse(resp)
    case 'GetOrderHistory': return new responses.GetOrderHistoryResponse(resp)
    case 'GetTickerHistory': return new responses.GetTickerHistoryResponse(resp)
    case 'GetTradesHistory': return new responses.GetTradesHistoryResponse(resp)
    case 'GetAccountInfo': return new responses.GetAccountInfoResponse(resp)
    case 'GetAccountPositions': return new responses.GetAccountPositionsResponse(resp)
    case 'GetAccountTrades': return new responses.GetAccountTradesResponse(resp)
    case 'GetDepositTickets': return new responses.GetDepositTicketsResponse(resp)
    case 'GetInstrument': return new responses.GetInstrumentResponse(resp)
    case 'GetInstruments': return new responses.GetInstrumentsResponse(resp)
    case 'GetOrderFee': return new responses.GetOrderFeeResponse(resp)
    case 'GetOrderStatus': return new responses.GetOrderStatusResponse(resp)
    case 'GetProducts': return new responses.GetProductsResponse(resp)
    case 'GetL2Snapshot': return new responses.GetL2SnapshotResponse(resp)
    case 'GetUserInfo': return new responses.GetUserInfoResponse(resp)
    case 'GetUserPermissions': return new responses.GetUserPermissionsResponse(resp)
    case 'GetWithdrawTickets': return new responses.GetWithdrawTicketsResponse(resp)
    case 'SendOrder': return new responses.SendOrderResponse(resp)
    case 'SubscribeAccountEvents': return new responses.SubscribeAccountEventsResponse(resp)
    case 'SubscribeLevel1': return new responses.SubscribeLevel1Response(resp)
    case 'SubscribeLevel1Markets': return new responses.SubscribeLevel1MarketsResponse(resp)
    case 'SubscribeLevel2': return new responses.SubscribeLevel2Response(resp)
    case 'SubscribeTicker': return new responses.SubscribeTickerResponse(resp)
    case 'SubscribeTrades': return new responses.SubscribeTradesResponse(resp)
    case 'UnsubscribeLevel1': return new responses.UnsubscribeLevel1Response(resp)
    case 'UnsubscribeLevel2': return new responses.UnsubscribeLevel2Response(resp)
    case 'UnsubscribeTicker': return new responses.UnsubscribeTickerResponse(resp)
    case 'UnsubscribeTrades': return new responses.UnsubscribeTradesResponse(resp)
    case 'CancelAllOrders': return new responses.CancelAllOrdersResponse(resp)
    case 'GetOpenOrders': return new responses.GetOpenOrdersResponse(resp)
    case 'CancelOrder': return new responses.CancelOrderResponse(resp)
    case 'Logout': return new responses.LogoutResponse(resp)
  }

  return new responses.FoxbitResponse(resp)
}
